---
title: "Brennan_Test"
author: "Brennan Thompson"
date: "2024-08-03"
output: html_document
---
```{r}
library(dplyr)
```


```{r}
df <- read.csv("C:/Users/Brennan Thompson/Documents/STAT6021/financial_independence/data/reddit_finance.csv")
```
```{r}
df
```
```{r}

```


```{r}
# Question 1 for Multiple Regression:
# PREDICTORS:
# number of incomes, 'num_incomes'
# age, "age"
# relationship status, "rel_status"
# children, "children"
# percentage of financial independence achieved, "fin_indy_pct", 
# stop working when independent, "stp_whn_fin_indy",
# safe withdrawal rate, "tgt_sf_wthdrw_rt", 
# Home value, "home_value",
# Brokerage Accounts (taxable), "brokerage_accts_tax"
# student_loans
# mortgage,
# auto_loan,
# credit_personal_loan,
# medical_debt,
# invst_prop_bus_own_debt,
# other_debt,
# 2020_gross_inc,
# 2020_housing_exp,
# 2020_utilities_exp,
# 2020_transp_exp,
# 2020_necessities_exp
# 2020_lux_exp
# 
# 2020_child_exp
# 
# 2020_debt_repay
# 
# 2020_invst_save
# 
# 2020_charity
# 
# 2020_healthcare_exp
# 
# 2020_taxes
# 
# 2020_edu_exp
# 
# 2020_other_exp
#
# 
#
# OUTPUT VAR:
# influence the Financial Independence (FI) number among American respondents? (AFNAN), 'fin_indy_num' and 'whn_fin_indy_num'
```

```{r}

```


```{r}
fin_df <- df %>% mutate(fin_indy_inst_amount = coalesce(fin_indy_num, 0) + coalesce(whn_fin_indy_num, 0))
```
```{r}
fin_df <- filter(fin_df, country == "United States")

fin_df <- select(fin_df, -c("rownames"))
 
```

```{r}
fin_df
```


```{r}
model_df <- fin_df %>%
  select(c(fin_indy_inst_amount,
           
           retire_invst_num,
           tgt_sf_wthdrw_rt,
           num_incomes,
           fin_indy_pct,
           home_value,
           tgt_sf_wthdrw_rt,
           fin_indy_pct,
           student_loans,
          mortgage,
           auto_loan,
           X2020_gross_inc,
           X2020_housing_exp,
          X2020_utilities_exp,
          X2020_transp_exp,
         X2020_necessities_exp,
           X2020_lux_exp,
           X2020_child_exp,
          X2020_debt_repay,
          X2020_invst_save,
           X2020_charity,
          X2020_healthcare_exp,
          X2020_taxes,
           X2020_edu_exp,




            age,
            fin_indy_pct


),
         )
model_df[is.na(model_df)] <- 0
```
#Dropped off after auto_loan ish
```{r}
model_df
```

```{r}
model1 <- lm(fin_indy_inst_amount~., data = model_df)
summary(model1)
```
```{r}
# As the tgt sf withdrawal rate goes down, as well as student loans
```

```{r}
model2 <- MASS::stepAIC(model1, direction = "both", trace )
summary(model2)
```

```{r}
car::vif(model2)
```




```{r}
car::vif(model1)

```


```{r}
final_df <- model_df %>% select(fin_indy_inst_amount,
                                retire_invst_num,
                                tgt_sf_wthdrw_rt,
                                num_incomes,  
                                fin_indy_pct,
                                home_value,
                                X2020_housing_exp,
                                X2020_lux_exp,
                                X2020_child_exp,
                                X2020_edu_exp)


model_df$predd <- predict(final_df)


```


```{r}
ind_pred<-mutate(na.omit(final_df), pred=fitted(model2), resid = residuals(model2))
view(ind_pred)
```


```{r}

ggplot(pranets_pred, aes(x=pred, y = resid))+geom_point()+
  geom_hline(yintercept=0, color = 'red')
```


```{r}
nrow(na.omit(final_df))
```


```{r}
```


```{r}
# Question 2:
#retirement investment amount, "retire_invst_num"
```

