---
title: "Cleaned Logistic Regression"
author: "Isaac Levy"
date: "2024-08-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(openintro)
library(nationalparkcolors)
library(PrettyCols)
library(MASS)
library(broom)
library(caret)
library(car)
library(glmnet)
library(pls)
library(corrr)
library(pROC)
library(tidyverse)


acadia <- park_palette('Acadia')
autumn <- prettycols('Autumn')
```

## Data Import and Cleaning

```{r}
data('reddit_finance') # from the openintro library

# select only respondants from the US
df <- reddit_finance[reddit_finance$country == 'United States',]

# remove all columns with more than 50% missing values
df.2 <- df[, which(colMeans(!is.na(df)) > 0.5)]

# remove all NAs in housing column
df.2 <- df.2[!is.na(df.2$housing),]

# recode housing variable to binary
df.2 <- df.2 %>%
  mutate(numown = ifelse(housing == 'Own', 1, 0))

# select only numeric columns and numown
df.numeric <- df.2 %>%
  select(c(numown, '2020_gross_inc', '2020_housing_exp', '2020_utilities_exp', 
           '2020_transp_exp', '2020_necessities_exp', '2020_lux_exp',
           '2020_invst_save', '2020_healthcare_exp', '2020_taxes', cash,
           retirement_accts_tax,brokerage_accts_tax, home_value, retire_exp,
           retire_invst_num, fin_indy_num, fin_indy_pct)) %>%
  na.omit()
```

## The Model

```{r}
# create princomp of remaining numeric variables
df.pca <- princomp(df.numeric[-1], fix_sign = T, cor = T)
# create dataframe with princomp scores and response variable
pca.dat <- data.frame(numown=df.numeric$numown, df.pca$scores)
# build logistic model will ~all~ components
logit.pca <- glm(numown~., data = pca.dat, family = binomial)
# use stepAIC to trim model
logit.pca.aic <- stepAIC(logit.pca, direction = 'both', trace = F, method = 'glm')
# summary of best model as determined by stepAIC
summary(logit.pca.aic)
```

## Model Predictions vs Observed

```{r}
# predictions
y_hat<- round(predict(logit.pca.aic, type = 'response'), 3)
# rounded predictions
y_hat_rounded <- ifelse(y_hat > .70, 1, 0)
# actual values
y <- pca.dat$numown
# residuals
resids <- round(residuals(logit.pca.aic, type = 'response'), 3)
# bind columns together
model.eval<- data.frame(cbind(y, y_hat_rounded, y_hat, resids))
head(model.eval)
```

### Residuals

```{r}
# PCA residuals look really good

model.eval %>%
  ggplot() +
  aes(x=resids) +
  geom_density(stat = 'count')
```

### Confusion Matrix

```{r}
expected.vals.pca <- factor(df.numeric$numown)
predicted.vals.pca <- factor(ifelse(predict(logit.pca.aic) > .7, 1, 0))
confuse.pca <- confusionMatrix(data = predicted.vals.pca,
                               reference = expected.vals.pca)
confuse.pca
```

### ROC Curve and Area Under Curve

```{r}
ctrl <- trainControl(method = 'cv', number = 10,
                     summaryFunction = twoClassSummary,
                     classProbs = T, savePredictions = T)

dat <- pca.dat

dat$numown <- ifelse(dat$numown == 1, 'DoesOwn', 'NotOwn')

logit.pca.train <- train(numown~., method = 'glm', data = dat,
                         family = binomial, trControl = ctrl, metric = 'ROC')
# i missed some steps here
predictions <- logit.pca.train$pred

roc <- roc(predictions$obs, predictions$DoesOwn)

roc.dat <- data.frame(TPR = roc$sensitivities, FPR = 1-roc$specificities)

ggplot(roc.dat, aes(x=FPR, y=TPR))+geom_line(color=autumn[1])
```

```{r}
roc
```



## Check Model Assumptions

### Relationship Between Log Odds and Components

```{r}
# create vector of log-odds
probabilities <- predict(logit.pca.aic, type = 'response')
logit = log(probabilities/(1-probabilities))
# combine log-odds with pca components
pca.dat.assumptions <- cbind(pca.dat, logit)
# melt dataframe to be able to facet wrap
model.df <- gather(pca.dat.assumptions, key = 'predictor', value = 'value', -c(logit, numown))
# graph log-odds vs principal components
model.df %>%
  ggplot() +
  aes(x=value, y=logit) +
  geom_jitter() +
  facet_wrap(predictor~., scale = 'free') +
  geom_smooth(method = 'glm', color=autumn[1])
```

### Multicollinearity

```{r}
vif(logit.pca.aic)
```


