---
title: "Vish_Test"
author: "VG_qtf7du"
date: "2024-07-25"
output: html_document
---
```{r}
library(tidyverse)
```
```{r}
#library(dataMaid)
#makeDataReport(fin_df,output = "html", replace = T)
```


```{r}
work_dir <- dirname(getwd())
work_dir
filepath <- paste(work_dir, "/data/reddit_finance.csv", sep = "")
fin_df <- read.csv(filepath)


fin_df <- filter(fin_df, country == "United States")
fin_df <- select(fin_df, -c("rownames"))
fin_df
```
```{r}
fin_df <- fin_df %>% mutate(fin_indy_inst_amount = coalesce(fin_indy_num, 0) + coalesce(whn_fin_indy_num, 0))
fin_df
```

```{r}
numeric_columns <- fin_df %>%
  select(where(is.numeric)
         ) %>%
  names()
numeric_columns

fin_df <- fin_df %>%
  mutate(across(all_of(numeric_columns), as.numeric))
```
```{r}
fin_df[is.na(fin_df)] <- 0
```

```{r}
#model1 <- lm(fin_indy_num~tgt_sf_wthdrw_rt+home_value+invst_accts+student_loans+medical_debt+
 #              X2020_housing_exp+X2020_lux_exp+X2020_charity+X2020_other_exp+max_retire_sup+brokerage_accts_tax+
  #             spec_crypto, fin_df)
model1 <- lm(fin_indy_inst_amount~.-fin_indy_num-whn_fin_indy_num-rownames, select(fin_df, numeric_columns))

aicm <- MASS::stepAIC(model1, direction = "both", trace = F)
#summary(aicm)
```
```{r}
round(cor(select(fin_df,numeric_columns)),2)
```


```{r}
library(ggcorrplot)
ggcorrplot(cor(select(fin_df,numeric_columns)), type="upper")
```

```{r}
ggplot(fin_df, aes(whn_fin_indy_num)) +
  geom_histogram(na.rm = TRUE, bins = 20) +
  labs(
    title = "At what amount invested did you consider\nyourself Financially Independent?",
    x = "Dollar Amount (in local currency)",
    y = "Number of Respondents"
  )
```
```{r}
ggplot(fin_df, aes(retire_age)) +
  geom_bar(na.rm = TRUE) +
  labs(
    title = "At what age do you expect to retire?",
    x = "Age Bracket",
    y = "Number of Respondents"
  )
```
```{r}
fin_df %>%
  ggplot(
    aes(x = fin_indy_num, y = retire_exp )
  )+
  geom_jitter()
#+ scale_x_log10() + scale_y_log10()
```

```{r}
fin_df %>%
  ggplot(
    aes(x=fin_indy_inst_amount, y = fin_indy_num)
  )+
  geom_jitter()+
  scale_y_sqrt()+
  scale_x_sqrt()
```

```{r}
df_long <- fin_df %>%
  select(numeric_columns) %>%
  pivot_longer(-fin_indy_inst_amount,names_to = "variable", values_to = "value")
df_long
```



```{r}
df_long %>%
  ggplot( aes(x = value, y = fin_indy_inst_amount)) +  # Use 'id' as y-axis
  geom_jitter() +  # or any other geom function
  facet_wrap(~variable) +
  labs(x = "Value", y = "ID", title = "Faceted Plot by Variable") +
  theme_minimal()
```
```{r}
fin_df %>% filter(fin_indy == "Yes") %>%
  ggplot(
    aes(x = cash, y=fin_indy_inst_amount)
  ) + 
  geom_jitter()+
  #scale_x_sqrt()+
  geom_smooth()
```
```{r}
pca <- princomp(fin_df%>% select(numeric_columns), cor = T, fix_sign = T)
summary(pca)
```

```{r}
pca$loadings
```

```{r}
biplot(pca)
```












```{r}
library(tidyverse)
```



```{r}
work_dir <- dirname(getwd())

filepath <- paste(work_dir, "/data/reddit_finance - vish - renamed_year_cols.csv", sep = "")
fin_df <- read.csv(filepath)

fin_df <- filter(fin_df, country == "United States")
# fin_df <- select(fin_df, -c("rownames"))

fin_df <- filter(fin_df, coalesce(retire_invst_num,0)>0 & coalesce(retire_invst_num,0)<10000000)
# fin_df <- filter(fin_df, retire_invst_num!=2500000 & retire_invst_num!=2000000)
nrow(fin_df)
get_mode <- function(v) {
  uniq_vals <- unique(v)
  uniq_vals[which.max(tabulate(match(v, uniq_vals)))]
}
get_mode(fin_df$retire_invst_num)
fin_df <- fin_df %>% mutate(retire_invst_num = (retire_invst_num)**(1/2))

fin_df <- fin_df %>% mutate(fin_indy_inst_amount = coalesce(fin_indy_num, 0) + coalesce(whn_fin_indy_num, 0))
fin_df %>% ggplot( aes(x = retire_invst_num)) + geom_histogram()

library("ggpubr")
ggqqplot(fin_df$retire_invst_num)
```

```{r}

### BASIC TRANSFORMATIONS
model_df <- fin_df %>% mutate(
  tgt_sf_wthdrw_rt = coalesce(as.numeric(tgt_sf_wthdrw_rt),3),
  tgt_sf_wthdrw_rt = ifelse(tgt_sf_wthdrw_rt < 15, tgt_sf_wthdrw_rt, NA),
  tgt_sf_wthdrw_rt = coalesce(tgt_sf_wthdrw_rt, mean(tgt_sf_wthdrw_rt)),
  
  retire_exp = coalesce(as.numeric(retire_exp),0),
  retire_exp = ifelse(retire_exp==0, mean(retire_exp), retire_exp),
  
  home_value = coalesce(home_value,0),
  
  brokerage_accts_tax = coalesce(brokerage_accts_tax,0),
  brokerage_accts_tax = ifelse(brokerage_accts_tax!=0,brokerage_accts_tax, mean(brokerage_accts_tax)),
  
  retirement_accts_tax = coalesce(retirement_accts_tax, 0),
  retirement_accts_tax = ifelse(retirement_accts_tax==0, mean(retirement_accts_tax), retirement_accts_tax),
  
  cash = coalesce(cash, 0),
  cash = ifelse(cash==0 | cash>100000, mean(cash), cash),
  
  invst_accts = coalesce(invst_accts, 0),
  invst_accts = ifelse(invst_accts==0 | invst_accts>100000, mean(invst_accts), invst_accts),
  
  spec_crypto = coalesce(spec_crypto, 0),
  # spec_crypto = ifelse(spec_crypto==0 | spec_crypto>100000, mean(spec_crypto), spec_crypto),
  
  invst_prop_bus_own = coalesce(invst_prop_bus_own,0),
  
  student_loans = coalesce(student_loans,0),
  
  other_val = coalesce(other_val,0),
  
  auto_loan = coalesce(auto_loan,0),
  
  credit_personal_loan = coalesce(credit_personal_loan,0),
  
  medical_debt = coalesce(medical_debt,0),
  
  Y2020_gross_inc = coalesce(Y2020_gross_inc,0),
  Y2020_housing_exp = coalesce(Y2020_housing_exp,0),
  Y2020_utilities_exp = coalesce(Y2020_utilities_exp,0),
  Y2020_transp_exp = coalesce(Y2020_transp_exp,0),
  Y2020_necessities_exp = coalesce(Y2020_necessities_exp,0),
  Y2020_lux_exp = coalesce(Y2020_lux_exp,0),
  Y2020_child_exp = coalesce(Y2020_child_exp,0),
  Y2020_debt_repay = coalesce(Y2020_debt_repay,0),
  Y2020_invst_save = coalesce(Y2020_invst_save,0),
  Y2020_charity = coalesce(Y2020_charity,0),
  Y2020_healthcare_exp = coalesce(Y2020_healthcare_exp,0),
  Y2020_taxes = coalesce(Y2020_taxes,0),
  Y2020_edu_exp = coalesce(Y2020_edu_exp,0),
  Y2020_other_exp = coalesce(Y2020_other_exp,0),

  
)



model_df <- model_df %>% mutate(
  fin_indy_inst_amount = (1 + fin_indy_inst_amount)**(1/4),
  invst_prop_bus_own = log (1+invst_prop_bus_own),
  Y2020_lux_exp = sqrt(1 + Y2020_lux_exp),
  Y2020_gross_inc = sqrt(1 + Y2020_gross_inc)
  
  )


model_df = select(model_df, c(retire_invst_num,
                              
    # children,
    
    fin_indy_inst_amount,
    tgt_sf_wthdrw_rt,
    retire_exp,
    home_value,
    brokerage_accts_tax,
    retirement_accts_tax,
    cash,
    invst_accts,
    spec_crypto,
    invst_prop_bus_own,
    other_val,
    student_loans,
    auto_loan,
    credit_personal_loan,
    medical_debt,

    Y2020_gross_inc,
    Y2020_housing_exp,
    Y2020_utilities_exp,
    Y2020_transp_exp,
    Y2020_necessities_exp,
    Y2020_lux_exp,
    Y2020_child_exp,
    Y2020_debt_repay,
    Y2020_invst_save,
    Y2020_charity,
    Y2020_healthcare_exp,
    Y2020_taxes,
    Y2020_edu_exp,
    Y2020_other_exp,

    
    


    
  )
)

model_df2 <- gather(model_df, key = "predictor", value = "value", -retire_invst_num)
model_df2

model_df2 %>%
  ggplot(
    aes(y = retire_invst_num, x = value)
  ) + 
  geom_jitter() + 
  facet_wrap(predictor ~ ., scale = "free") + 
  geom_smooth(method = "lm")
```

```{r}

model <- lm(retire_invst_num~., model_df)
summary(model)
```
```{r}
cor(model_df)
```
```{r}
car::vif(model)
```

```{r}
aic_model <- MASS::stepAIC(model, direction = "both", trace = F)
summary(aic_model)
```
```{r}

aic_model_df <- select(model_df, 
                       retire_invst_num,
fin_indy_inst_amount ,
tgt_sf_wthdrw_rt ,
retire_exp ,
home_value ,
brokerage_accts_tax ,
retirement_accts_tax ,
other_val ,
auto_loan ,
medical_debt ,
Y2020_gross_inc ,
Y2020_housing_exp ,
Y2020_invst_save,

  
  
  
  
  
  
  )
library(broom)
diagnostics <- model %>%
  augment(data = na.omit(aic_model_df)) 
diagnostics
```


```{r}
outlier <- filter(diagnostics, abs(.std.resid)>3)
outlier
```

```{r}
influence <- filter(diagnostics, abs(.cooksd) > 4/nrow(aic_model_df) )
influence
```

```{r}
aic_model_df2 <- filter(diagnostics, abs(.std.resid)<3)
model2 = lm(retire_invst_num~.,select(aic_model_df2, -starts_with(".")))
summary(model2)
```
```{r}
diagnostics2 <- model %>%
  augment(data = na.omit(aic_model_df)) 
diagnostics2 %>% ggplot(aes(x = .fitted,y = .resid)) + geom_jitter()
```







